### PR TITLE
[dev] Make mockgun string comparison case insensitive (RDEV-15305)

### PR DESCRIPTION
**Pull request by rlessardrodeofx**
#### Purpose of the PR

This PR ensure that mockgun comparison of text fields are case insensitive.
This is the case for a real Shotgun instance.

After this is approved I will do an official PR upstream.

#### Overview of the changes

* Do lowercase comparison for text fields
* Add unit-tests

#### Type of feedback wanted

Any kind of feedback. 
Is there some other situations where case sensitivity matter that I did not test?

#### Where should the reviewer start looking at?

Diff should be enough

#### Potential risks of this change

Some tests that where using mockgun could start failing (which in my case is what I want).

#### Relationship with other PRs

None

### CODE REVIEW

**Review by Zaltu — APPROVED** [review]
I don't see a reason to not do this for us here. In terms of eventually pushing this upstream, I believe based on the recent updates to Shotgun itself that the longer-term goal for them is to let the user decide whether a field should be case-sensitive or not (which as you know is already the case for filed tagged as unique per project).
This would probably be a good thing to open a ticket about and ask them their official plans for. I can do that if that sounds right.

**Review by swaugh-rodeo — APPROVED** [review]
Woop forgot which account I was on

**Comment by rlessardrodeofx** [comment]
> This would probably be a good thing to open a ticket about and ask them their official plans for. I can do that if that sounds right.

That would be great! If such an option appear I expect it to be visible in the schema and in that case the code should be straightforward to adapt.

**Comment by JeanChristopheMorinPerso** [comment]
Do we have an upstream PR for this?

**Comment by JeanChristopheMorinRodeoFX** [comment]
@rlessardrodeofx Do we have a PR opened on the upstream repo for this? What do the Shotgun guys think?

**Comment by rlessardrodeofx** [comment]
I've opened a PR upstream here:
https://github.com/shotgunsoftware/python-api/pull/217

**Comment by JeanChristopheMorinRodeoFX** [comment]
Thanks, can you update the ticket we have with Shotgun with the link to the PR so they have someone on their end that take some time to look at it please? See https://support.shotgunsoftware.com/hc/en-us/requests/106863

**Comment by rlessardrodeofx** [comment]
Done!

**Pull request merged**
