### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by gst**
All in title : 

steps followed:

+ git checkout rdo_master
+ git checkout -b sync_with_upstream
+ git remote update && git merge upstream/master  # upstream being my remote to shotgunsofware 
+ resolved little conflict
+ git push origin
+ created this PR

### CODE REVIEW

**Review by darkvertex — APPROVED** [review]
Generally LGTM

**Comment by JeanChristopheMorinRodeoFX** [comment]
@gst can you check and tell me if we have any custom stuff in it at that point? I am under the impression that our changes were all merged in upstream. If so, I would simply drop our fork I guess...?

**Comment by gst** [comment]
I didnt make the actual diff but i am mostly sure we are still ahead of them..

**Comment by rodeo** [comment]
@JeanChristopheMorin 

we are still a bit ahead : 

`in` operator + `currency` field + one docstring

but I'm a bit surprised by this diff we have over upstream:

```
-                                   "date": datetime.date,
+                                   "date": basestring
```

why is that ? 
cause it's not normal to me..
@swaugh-rodeo  do you have any idea / advice on that ?


the full diff vs **upstream/master**  because it's small : 

```
✔ ~/rdoenv/rdo_shotgun_api3 [sync_with_upstream|✔] 
10:14 $ git diff upstream/master -- shotgun_api3
diff --git a/shotgun_api3/lib/mockgun/mockgun.py b/shotgun_api3/lib/mockgun/mockgun.py
index 9eb5a8b..94bb19d 100644
--- a/shotgun_api3/lib/mockgun/mockgun.py
+++ b/shotgun_api3/lib/mockgun/mockgun.py
@@ -459,12 +459,14 @@ class Shotgun(object):
                     sg_type = field_info["data_type"]["value"]
                     python_type = {"number": int,
                                    "float": float,
+                                   "currency": float,
                                    "checkbox": bool,
                                    "percent": int,
                                    "text": basestring,
                                    "serializable": dict,
-                                   "date": datetime.date,
+                                   "date": basestring,
                                    "date_time": datetime.datetime,
+                                   "duration": int,
                                    "list": basestring,
                                    "status_list": basestring,
                                    "url": dict}[sg_type]
@@ -608,6 +610,10 @@ class Shotgun(object):
                 if rval is None:
                     return len(lval) != 0
                 return rval["id"] not in (sub_lval["id"] for sub_lval in lval)
+            elif operator == 'in':
+                if rval is None:
+                    return len(lval) != 0
+                return all(element['id'] in (sub_lval['id'] for sub_lval in lval) for element in rval)
 
         raise ShotgunError("The %s operator is not supported on the %s type" % (operator, field_type))
 
@@ -766,8 +772,13 @@ class Shotgun(object):
         else:
             raise ShotgunError("%s is not a valid filter operator" % filter_operator)
 
-
     def _update_row(self, entity_type, row, data):
+        """For a given row of the 'database', update the row with the given data.
+        
+        :param str entity_type: shotgun entity.
+        :param dict row: current definition of the row.
+        :param dict data: data to inject in the row.
+        """
         for field in data:
             field_type = self._get_field_type(entity_type, field)
             if field_type == "entity" and data[field]:
@@ -776,7 +787,6 @@ class Shotgun(object):
                 row[field] = [{"type": item["type"], "id": item["id"]} for item in data[field]]
             else:
                 row[field] = data[field]
-            
 
     def _validate_entity_exists(self, entity_type, entity_id):
         if entity_id not in self._db[entity_type]:
✔
```

**Comment by swaugh-rodeo** [comment]
Mockgun is just a glorified testing environment. Could be that either someone changed our version to take strings to avoid having to deal with full datetime objects, or mockgun itself originally just took strings and now they want to also be able to test the meme-y stuff that goes on with datetimes.

I wouldn't call it a bit deal. No idea how much we use mockgun, but it *shouldn't* affect anything under normal circumstances.

**Comment by gst** [comment]
good for you @JeanChristopheMorin  ?

**Comment by JeanChristopheMorinRodeoFX** [comment]
@swaugh-rodeo can you look into the shotgun-api repo and see if our PRs are stil there? If not, can you create a PR with our changes and see with the Shotgun team if they could merge them please?

**Comment by JeanChristopheMorinRodeoFX** [comment]
apart from that, looks good to me. But would like to get rid of our fork as soon as our changes are merged in uptream repo.

**Review by JeanChristopheMorinRodeoFX — APPROVED** [review]

**Comment by swaugh-rodeo** [comment]
@JeanChristopheMorin I can, but I have no real idea why any of the changes were initially made. Might be better for someone who actually edited those lines to own that since they (presumable) know why they did stuff.

If no one knows why these changes, I'll handle it though.¯\_(ツ)_/¯

**Comment by swaugh-rodeo** [comment]
Looks like Jordi made most/all of the changes :thinking: 
He's *with* Shotgun now, right? I can arrange for him to handle the merge.

**Comment by gst** [comment]
git blame is your friend ;)

=>

https://github.com/rodeofx/python-api/pull/5
https://github.com/rodeofx/python-api/commit/e9b0575be9e859d5aad1d6770b547e7024e71d32
https://github.com/rodeofx/python-api/commit/13a61d9cf0a707b6969540b65235b27c972f2bf0 (this one isn't very clear)

**Comment by swaugh-rodeo** [comment]
I'm not sure how @rodeo ended up with so few differences.
Just checking with 
https://github.com/shotgunsoftware/python-api/compare/master...rodeofx:sync_with_upstream
shows we have a fair number of differences with upstream/master, including some rodeo-specific changes. Unless we only want to compare shotgun.py, in which case we have no changes.

Unless I'm missing something... @gst @JeanChristopheMorin

**Comment by gst** [comment]
we needed these changes/adds in mockgun for our own tests I can only say :) 

the only change I'm pretty sure that should NOT be merged upstream is probably this : 

```
-                                   "date": datetime.date,
+                                   "date": basestring,
```

and maybe we should/could revert it ; the rest of the changes are addition only anyway.

**Comment by swaugh-rodeo** [comment]
It'd be nice to revert it and see what happens at least. It's kind of unclear whether these changes are actually beneficial as a whole or are ways to play nice with our tests.

**Comment by JeanChristopheMorinRodeoFX** [comment]
Closing in favor of https://github.com/rodeofx/python-api/pull/14

**Pull request closed without merging**
